spring:
  datasource:
    url: jdbc:h2:mem:catalogue
    username: sa
    password:
    driverClassName: org.h2.Driver
  profiles:
    active: default
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
